import { requireStaffPage } from '@/lib/access';
import { CircleDollarSign, Clock3, Target, UsersRound } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { listLeads, listProjects, listReviews } from '@/db/store';

export const dynamic = 'force-dynamic';

export default async function ReportsPage() {
  await requireStaffPage();
  const [leads, projects, reviews] = await Promise.all([listLeads(), listProjects(), listReviews()]);
  const revenue = projects.reduce((sum, project) => sum + project.value, 0); const won = leads.filter((lead) => ['booked', 'won'].includes(lead.status)).length;
  const months = [['Mar', 28], ['Apr', 38], ['May', 44], ['Jun', 52], ['Jul', 66], ['Aug', 82]];
  return <AppShell active="reports" eyebrow="Business intelligence" title="See what creates growth." subtitle="Track the full customer lifecycle, from first conversation to revenue and reputation.">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[CircleDollarSign, `$${revenue.toLocaleString()}`, 'Active project value', 'Current records'], [UsersRound, leads.length, 'Opportunities', 'Current records'], [Target, `${Math.round((won / Math.max(1, leads.length)) * 100)}%`, 'Booking rate', 'Current records'], [Clock3, 'Not tracked', 'First response', 'No provider']].map(([Icon, value, label, change]) => { const Item = Icon as typeof Target; return <Card key={String(label)} className="border-0 ring-1 ring-foreground/[0.075]"><CardContent className="p-5"><div className="flex justify-between"><Item className="size-4 text-[#628d28]" /><Badge className="bg-primary/15 text-[#466b13]">{String(change)}</Badge></div><p className="mt-4 text-3xl font-black tracking-tight">{String(value)}</p><p className="mt-1 text-xs text-muted-foreground">{String(label)}</p></CardContent></Card>})}</div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_0.8fr]"><Card className="border-0 ring-1 ring-foreground/[0.075]"><CardHeader><CardTitle>Customer journey momentum</CardTitle><CardDescription>Illustrative chart only. Historical events are not tracked.</CardDescription></CardHeader><CardContent><div className="flex h-64 items-end gap-3 rounded-xl bg-muted/35 p-4">{months.map(([month, value]) => <div key={String(month)} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="group relative rounded-t-lg bg-[#15251f] transition-colors hover:bg-[#294439]" style={{ height: `${value}%` }}><span className="absolute -top-6 left-1/2 -translate-x-1/2 text-[10px] font-bold">{value}</span></div><span className="text-center text-[10px] font-semibold text-muted-foreground">{month}</span></div>)}</div></CardContent></Card><Card className="border-0 ring-1 ring-foreground/[0.075]"><CardHeader><CardTitle>Lifecycle conversion</CardTitle><CardDescription>Current record counts; bar widths are illustrative.</CardDescription></CardHeader><CardContent className="space-y-4">{[['Lead captured', leads.length, 100], ['Conversation started', 'Not tracked', 0], ['Booking confirmed', won, 58], ['Project active', projects.length, 46], ['Review received', reviews.length, 38]].map(([label, value, width]) => <div key={String(label)}><div className="flex items-center justify-between text-xs"><span>{label}</span><span className="font-bold">{value}</span></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${width}%` }} /></div></div>)}<div className="rounded-xl bg-primary/12 p-3 text-xs leading-5"><span className="font-semibold">Best next move:</span> reduce proposal response time by connecting instant booking to qualified leads.</div></CardContent></Card></div>
  </AppShell>;
}
