import { MessageCircleHeart, Send, ShieldCheck, Star, TrendingUp } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { ReviewActions } from '@/components/review-actions';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { listReviews } from '@/db/store';

export const dynamic = 'force-dynamic';

export default async function ReviewsPage() {
  const reviews = await listReviews(); const average = reviews.reduce((sum, item) => sum + item.rating, 0) / Math.max(1, reviews.length);
  return <AppShell active="reviews" eyebrow="Customer reputation" title="Turn great delivery into public trust." subtitle="Request honest feedback, protect unhappy customers with a private recovery path, and publish approved testimonials.">
    <div className="grid gap-3 sm:grid-cols-4">{[[Star, average.toFixed(1), 'Average rating'], [Send, '61', 'Requests sent'], [MessageCircleHeart, reviews.filter((item) => item.status === 'published').length, 'Published'], [ShieldCheck, reviews.filter((item) => item.status === 'private').length, 'Private recovery']].map(([Icon, value, label]) => { const Item = Icon as typeof Star; return <Card key={String(label)} className="border-0 ring-1 ring-foreground/[0.075]"><CardContent className="p-5"><Item className="size-4 text-[#628d28]" /><p className="mt-3 text-2xl font-black">{String(value)}</p><p className="text-xs text-muted-foreground">{String(label)}</p></CardContent></Card>})}</div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.6fr)_360px]"><Card className="border-0 ring-1 ring-foreground/[0.075]"><CardHeader><CardTitle>Feedback inbox</CardTitle><CardDescription>Review every customer response before it appears publicly.</CardDescription></CardHeader><CardContent className="space-y-3">{reviews.map((review) => <div key={review.id} className="rounded-2xl border border-border bg-background p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-muted text-xs font-black">{review.customer.split(' ').map((part) => part[0]).join('').slice(0,2)}</span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{review.customer}</p><div className="flex">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className={`size-3.5 ${index < review.rating ? 'fill-[#8dbf39] text-[#8dbf39]' : 'text-border'}`} />)}</div><Badge variant="outline" className="capitalize">{review.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{review.service}</p><p className="mt-3 text-sm leading-6">“{review.quote}”</p></div><ReviewActions id={review.id} status={review.status} /></div></div>)}</CardContent></Card>
      <div className="space-y-4"><Card className="border-0 bg-[#15251f] text-white ring-1 ring-black/5"><CardHeader><CardTitle>Campaign performance</CardTitle><CardDescription className="text-white/52">Last 30 days</CardDescription></CardHeader><CardContent className="space-y-4">{[['Completed jobs', 82, 100], ['Requests delivered', 67, 82], ['Feedback received', 38, 46], ['Public reviews', 31, 38]].map(([label, value, width]) => <div key={String(label)}><div className="flex justify-between text-xs"><span className="text-white/65">{label}</span><span className="font-bold">{value}</span></div><div className="mt-2 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-primary" style={{ width: `${width}%` }} /></div></div>)}</CardContent></Card><Card className="border-0 ring-1 ring-foreground/[0.075]"><CardContent className="p-5"><TrendingUp className="size-5 text-[#628d28]" /><p className="mt-3 font-bold">Review velocity is up 24%</p><p className="mt-1 text-sm leading-6 text-muted-foreground">The best response rate is 24 hours after project completion.</p></CardContent></Card></div></div>
  </AppShell>;
}
