import { Link } from '@/components/plain-link';
import { ArrowLeft, Check, Clock3, Download, FileText, MessageSquareText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { getProjectByToken } from '@/db/store';

export const dynamic = 'force-dynamic';

export default async function ClientPortalPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params; const project = await getProjectByToken(token);
  if (!project) return <main className="grid min-h-screen place-items-center bg-[#f6f2e8] p-6 text-[#17372f]"><div className="text-center"><p className="text-3xl font-black">Portal not found</p><Button render={<Link href="/clients" />} variant="outline" className="mt-5"><ArrowLeft />Return to projects</Button></div></main>;
  return <main className="min-h-screen bg-[#f6f2e8] text-[#17372f]"><header className="border-b border-[#17372f]/10 bg-[#fffdf7]"><div className="mx-auto flex max-w-6xl items-center gap-4 px-5 py-5"><span className="grid size-10 place-items-center rounded-xl bg-[#b8ff4e] font-black">N</span><div><p className="font-black">Northstar Services</p><p className="text-xs text-[#17372f]/55">Secure client workspace</p></div><Button render={<Link href="/clients" />} variant="outline" className="ml-auto"><ArrowLeft />Studio dashboard</Button></div></header><section className="mx-auto max-w-6xl px-5 py-12"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-[#618c2d]">Welcome back, {project.client.split(' ')[0]}</p><h1 className="mt-3 text-5xl font-black tracking-[-0.06em]">Everything is moving.</h1><p className="mt-3 text-[#17372f]/62">{project.project} is {project.progress}% complete.</p></div><div className="rounded-2xl bg-[#17372f] px-5 py-4 text-white"><p className="text-3xl font-black">{project.deliverables}</p><p className="text-xs text-white/58">deliverables ready</p></div></div><Progress value={project.progress} className="mt-8 h-3" /><div className="mt-8 grid gap-4 lg:grid-cols-[1.3fr_0.7fr]"><div className="grid gap-4 sm:grid-cols-2">{[['Next decision', project.next_action, Check], ['Latest update', 'The current project phase is ready for your review.', MessageSquareText], ['Project status', project.status, Clock3], ['Invoice', project.invoice_status, FileText]].map(([label, value, Icon]) => { const Item = Icon as typeof Check; return <article key={String(label)} className="rounded-3xl border border-[#17372f]/10 bg-[#fffdf7] p-6"><Item className="size-5 text-[#618c2d]" /><p className="mt-8 text-xs font-bold uppercase tracking-[0.1em] text-[#17372f]/50">{String(label)}</p><p className="mt-2 text-lg font-black">{String(value)}</p><Button disabled variant="outline" className="mt-5">Preview only</Button></article>})}</div><aside className="rounded-3xl bg-[#17372f] p-6 text-white"><p className="text-xl font-black">File layout preview</p><p className="mt-2 text-sm leading-6 text-white/55">Illustrative filenames only. Downloads and approvals require implementation.</p><div className="mt-6 space-y-2">{['Project brief.pdf', 'Service checklist.pdf', 'Final schedule.pdf'].slice(0, project.deliverables || 1).map((file) => <button disabled key={file} className="flex w-full items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-3 text-left text-sm hover:bg-white/10"><FileText className="size-4 text-[#b8ff4e]" /><span className="flex-1">{file}</span><Download className="size-4 text-white/50" /></button>)}</div></aside></div></section></main>;
}
