import { Bot, CheckCheck, Clock3, Mail, MessageSquareText, Sparkles } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { listConversations, listLeads } from '@/db/store';

export const dynamic = 'force-dynamic';

export default async function InboxPage() {
  const [conversations, leads] = await Promise.all([listConversations(), listLeads()]);
  const selected = conversations[0]; const lead = leads.find((item) => item.id === selected?.lead_id);
  return <AppShell active="inbox" eyebrow="Unified inbox" title="One conversation, full context." subtitle="Website, email, and follow-up replies arrive with the customer history already attached.">
    <div className="grid min-h-[610px] overflow-hidden rounded-2xl border border-border bg-card shadow-sm lg:grid-cols-[330px_minmax(0,1fr)_310px]">
      <div className="border-b border-border lg:border-b-0 lg:border-r"><div className="flex items-center justify-between border-b p-4"><p className="font-bold">Conversations</p><Badge>{conversations.filter((item) => item.unread).length} new</Badge></div>{conversations.map((conversation, index) => <button key={conversation.id} className={`w-full border-b p-4 text-left ${index === 0 ? 'bg-primary/10' : 'hover:bg-muted/40'}`}><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${conversation.unread ? 'bg-primary' : 'bg-border'}`} /><p className="flex-1 text-sm font-semibold">{conversation.name}</p><span className="text-[10px] text-muted-foreground">Now</span></div><p className="mt-2 text-xs font-medium">{conversation.subject}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{conversation.preview}</p><Badge variant="outline" className="mt-2">{conversation.channel}</Badge></button>)}</div>
      <div className="flex min-h-[520px] flex-col"><div className="flex items-center gap-3 border-b p-4"><span className="grid size-10 place-items-center rounded-xl bg-muted text-xs font-black">{selected?.name.split(' ').map((part) => part[0]).join('').slice(0,2)}</span><div><p className="font-semibold">{selected?.name}</p><p className="text-xs text-muted-foreground">{selected?.subject}</p></div><Badge className="ml-auto bg-primary/15 text-[#466b13]">{selected?.intent}</Badge></div><div className="flex-1 space-y-5 p-5"><div className="max-w-[78%] rounded-2xl rounded-tl-sm bg-muted p-4 text-sm leading-6">{selected?.preview}</div><div className="ml-auto max-w-[78%] rounded-2xl rounded-tr-sm bg-[#15251f] p-4 text-sm leading-6 text-white">Hi {selected?.name.split(' ')[0]}, yes, we can help before your handover. I have checked the team schedule and reserved a suitable window. Would you like the standard or detailed move-out package?</div><div className="flex items-center justify-end gap-1 text-[11px] text-muted-foreground"><CheckCheck className="size-3" />Delivered by Maya</div><div className="rounded-xl border border-primary/30 bg-primary/8 p-3 text-xs leading-5"><span className="inline-flex items-center gap-1 font-semibold"><Sparkles className="size-3 text-[#628d28]" />Suggested next step</span><p className="mt-1 text-muted-foreground">Send the package comparison and booking link. The customer has a fixed date and high purchase intent.</p></div></div><div className="border-t p-4"><div className="flex items-end gap-2 rounded-xl border bg-background p-2"><textarea className="min-h-16 flex-1 resize-none bg-transparent p-2 text-sm outline-none" placeholder="Write a reply..." /><Button>Send reply</Button></div></div></div>
      <div className="border-t border-border bg-muted/25 p-5 lg:border-l lg:border-t-0"><p className="text-xs font-semibold uppercase tracking-[0.1em] text-muted-foreground">Customer context</p><div className="mt-4 space-y-4"><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Opportunity value</p><p className="mt-1 text-xl font-black">${lead?.value.toLocaleString() ?? '0'}</p><Badge variant="outline" className="mt-2 capitalize">{lead?.status}</Badge></CardContent></Card>{[[Mail, lead?.email], [Clock3, 'First reply in 48 seconds'], [MessageSquareText, selected?.channel], [Bot, 'Assistant qualified intent']].map(([Icon, text], index) => { const Item = Icon as typeof Mail; return <div key={index} className="flex items-start gap-3 text-xs"><Item className="mt-0.5 size-4 text-muted-foreground" /><span>{String(text ?? '')}</span></div>})}<Button variant="outline" className="w-full">Open customer record</Button></div></div>
    </div>
  </AppShell>;
}
